### ISSUE TITLE
PlayoutBee

### ISSUE THREAD

**Issue by SNRSE** [bitfocus/companion-module-bytehive-playoutbee#1]
Hey,
I am the developer of Playoutbee a Software that emulates a Hyperdeck. I would love to make it Controllable via Companion, at the moment it has an HTTP-API but could also be controlled directly via socket.io. Could someone please point me to a guide or a way I could do this ? is there a guide on how to create a Module for Companion?

**Comment by estilles** [comment]
Thanks @josephdadams!
