### ISSUE TITLE
Playoutbee ClipID Handling

### ISSUE THREAD

**Issue by amarkwalder** [bitfocus/companion-module-bytehive-playoutbee#11]
Hi

If we report back the ClipID number we got from playoutbee, why is +1 added in api.js to the ClipID? If we really want to report back what we got from playoutbee, then this +1 should be avoided as well. Am I wrong?

At the end we report something wrong to companion, if we have no clips, index of ClipID is 0 even if we don't have any clips and the name and Id of the current clip is most probably wrong.

A bug should be reported to playoutbee. IMHO it should be the following way (from playoutbee API):
- no clips: ClipID = -1 (--> That's currently not the case)
- 1 clip: ClipID = 0
- larger than 1 clip: ClipID > 0

What do you think?

Regards
André

**Comment by SNRSE** [comment]
playout bee V2 is now using unique ID's and indexes so this should be resolved with version 1.9.0 and later
