### ISSUE TITLE
PlayOutBee Initializing

### ISSUE THREAD

**Issue by TBuTcher71** [bitfocus/companion-module-bytehive-playoutbee#24]
Set IP and Port to 3000 but Status stays at Initializing

system: ** Starting Connection from "/Applications/Companion.app/Contents/Resources/bundled-modules/bytehive-playoutbee/main.js" **
system: ** Connection started **
Starting up module class: p
Sentry disabled
Module-host accepted registration

never continues

**Comment by SNRSE** [comment]
Hey, 
On the PlayoutBee Side, do you have at least 1 Asset? 
Or do you have an empty List ?
What version of playoutBee do you use?

**Comment by TBuTcher71** [comment]
Thanks MateYes 9 assets and it is working via web interface just not with Companion 3.0.1

I am using playoutbee raspberry pi 0.9.3?? I think
I have other things installed to your install so if I am to update to a newer version can we do it via just charging out the Playoutbee app in the pi image instead of replacing the whole thing?
i sent you an email directly as well.

**Comment by SNRSE** [comment]
Hey PlayoutBee 0.9.3 is no longer supported by Companion 3. Upgrade PlayoutBee or downgradeCOmpanion to 2.4.2
